# Generated by Django 5.2 on 2025-05-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grad_school', '0002_alter_menuitem_options_alter_time_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainbanner',
            name='video_url',
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='video_img',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to=''),
        ),
    ]
