# Generated by Django 5.2 on 2025-05-15 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grad_school', '0004_remove_mainbanner_video_img_mainbanner_video_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogNames',
            new_name='BlockNames',
        ),
        migrations.AlterModelOptions(
            name='blocknames',
            options={'verbose_name': 'Block Names', 'verbose_name_plural': 'Block Names'},
        ),
    ]
