# Generated by Django 5.2 on 2025-05-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grad_school', '0005_rename_blognames_blocknames_alter_blocknames_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
        migrations.RenameField(
            model_name='time',
            old_name='volue',
            new_name='value',
        ),
    ]
