# Generated by Django 5.2 on 2025-05-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grad_school', '0006_alter_time_options_rename_volue_time_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='title',
            new_name='class_name',
        ),
    ]
