# Generated by Django 5.2 on 2025-05-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grad_school', '0007_rename_title_time_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
